title: "Christians at CUH"
description: "Fellowship, prayer and encouragement at Cambridge University Hospitals"

# Use Minimal Mistakes via GitHub (no local install needed)
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "sunrise"

# Navigation bar items
navigation:
  - title: "Home"
    url: /
  - title: "Calendar"
    url: /calendar/
  - title: "About"
    url: /about/
  - title: "Links"
    url: /links/

# Default page layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

      include:
  - assets/css/custom.css
