title: ""
description: "Fellowship, prayer and encouragement at Cambridge University Hospitals"

url: "https://joelchin.github.io"
baseurl: "/ccicuh"

# âœ… Masthead settings
masthead_title: false            # completely hide text
logo: "/assets/images/ccicuhlogo.svg"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

header:
  overlay: false
  show_overlay_excerpt: false

navigation:
  - title: "Home"
    url: /
  - title: "Calendar"
    url: /calendar/
  - title: "About"
    url: /about/
  - title: "Links"
    url: /links/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
