logo: "/assets/images/cicuhlogo.svg"
title: "Christians in CUH"
description: "Fellowship, prayer and encouragement at Cambridge University Hospitals"

url: "https://joelchin.github.io"   # or later: "https://cuhchristians.com"
baseurl: "/cicuh"                   # remove this line once you move to a root domain


# Use Minimal Mistakes via GitHub (no local install needed)
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

# Navigation bar items
navigation:
  - title: "Home"
    url: /
  - title: "Calendar"
    url: /calendar/
  - title: "About"
    url: /about/
  - title: "Links"
    url: /links/

# Default page layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

      include:
  - assets/css/custom.css
  
### Upcoming Meetings (preview)


