title: "Connecting Christians in CUH"
description: "Fellowship, prayer and encouragement at Cambridge University Hospitals"

url: "https://cicuh.info"
baseurl: ""   # remove /cicuh, since youâ€™re now at the root domain

masthead_title: "CICUH"   # text in the top-left

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

analytics:
  provider: "google-gtag"   # use "google" for old Universal Analytics
  google:
    tracking_id: "G-625N3EYVB4"   # replace with your GA4 Measurement ID
    anonymize_ip: false           # optional

header:
  overlay: false
  show_overlay_excerpt: false

navigation:
  - title: "Home"
    url: /
  - title: "Calendar"
    url: /calendar/
  - title: "About"
    url: /about/
  - title: "Links"
    url: /links/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
