title: "Christians in CUH"
description: "Fellowship, prayer and encouragement at Cambridge University Hospitals"

url: "https://joelchin.github.io"
baseurl: "/cicuh"

# âœ… Root-level settings
masthead_title: ""                   # disables text in masthead
logo: "/assets/images/cicuhlogo.svg" # logo path

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

header:
  overlay: false
  show_overlay_excerpt: false
  logo: "/assets/images/cicuhlogo.svg"
  title: ""
  description: ""

navigation:
  - title: "Home"
    url: /
  - title: "Calendar"
    url: /calendar/
  - title: "About"
    url: /about/
  - title: "Links"
    url: /links/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
